//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TvcK22CNT1Lesson11.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class NvtTaiKhoan
    {
        public int NvtId { get; set; }
        public string NvtUserName { get; set; }
        public string NvtPassword { get; set; }
        public string NvtFullName { get; set; }
        public Nullable<int> NvtAge { get; set; }
        public string NvtEmail { get; set; }
        public string NvtPhone { get; set; }
        public Nullable<bool> NvtStatus { get; set; }
    }
}
